version: '3'

services:

  nginx:
    image: poktnetwork/nginx:dispatch
    build: ../nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx/conf.d/10-pocket.conf:/etc/nginx/conf.d/default.conf"
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - pocket

  # https://zcoin.io/znodes-specifications-release-founders-rewards-reduction/
  zcoin-mainnet:
    image: zcoinofficial/zcoind 
    command: -server -rest -listen -whitelist=0.0.0.0 -rpcallowip=0.0.0.0  
    volumes:
      - zcoin-mainnet:/home/zcoind/.zcoin
    expose:
      - "8888"
      - "8168"
    networks:
      - pocket

  pocket-service:
    image: poktnetwork/pocket-core:${ENV:-mvp-staging-latest}
    ports:
      - "8081:8081"
    command: --datadirectory datadir --disip ${POCKET_DISPATCH_IP:-dispatch.pokt.network} --gid ${POCKET_SERVICE_GID} --ip localhost --disrport 80 --port 8081 --requestTimeout 0
    environment:
      POCKET_CORE_START_DELAY: 10 
      POCKET_CORE_CHAINS: '[ { "blockchain": { "name": "ZCOIN", "netid": "MAINNET", "version": "0" }, "url": "zcoin-mainnet:8888" } ]'
    networks:
      - pocket
    restart: always

volumes:
  zcoin-mainnet:

networks:
  pocket:
    driver: bridge
