version: '3.4'
services:
  pocket-core.public.dappnode.eth:
    image: 'pocket-core.public.dappnode.eth:0.2.0'
    build: ./build/
    volumes:
      - 'data:/home/app/.pocket/'
    ports:
      - '8081:8081'
      - '26656:26656'
      - '26657:26657'
      - '46656:46656'
    environment:
      - POCKET_CORE_KEY
      - POCKET_CORE_CONFIG
      - POCKET_CORE_GENESIS
      - POCKET_CORE_PASSPHRASE
      - POCKET_CORE_CHAINS
    restart: on-failure
volumes:
  data: {}
