version: '3.4'
services:
  pocket-core.public.dappnode.eth:
    image: 'pocket-core.public.dappnode.eth:0.0.4'
    build: ./build
    volumes:
      - 'data:/usr/src/app/'
    ports:
      - '38081:8081'
    environment:
      - POCKET_CORE_SERVICE_GID=
      - POCKET_CORE_REQUEST_TIMEOUT=0
      - POCKET_CORE_SERVICE_IP=
      - POCKET_CORE_SERVICE_PORT=38081
volumes:
  data: {}
