version: "3.8"

# REF: https://www.cloudbooklet.com/how-to-install-nginx-and-lets-encrypt-with-docker-ubuntu-20-04/

x-loki:
  &loki-logging
  driver: loki
  options:
    loki-url: "http://localhost:3100/loki/api/v1/push"
    max-size: '5m'
    max-file: '3'
    keep-file: 'false'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./proxy/conf.d:/etc/nginx/templates
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/nginx/ssl
      - ./proxy/certbot/data:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - prometheus
      - grafana
    restart: unless-stopped
    logging: *loki-logging

  certbot-renew:
    image: certbot-renew
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    build: 
     context: certbot/
     dockerfile: Dockerfile 
    container_name: certbot-renew

  node1:
    image: poktnetwork/pocket:RC-0.7.0.1 
    container_name: node1 
    command: ["pocket", "start", "--keybase=false", "--mainnet", "--datadir=/home/app/.pocket/"]
    environment:
     - POCKET_CORE_PASSPHRASE=${POCKET_CORE_PASSPHRASE_NODE}
     - POCKET_CORE_KEY=""
     - GODEBUG="madvdontneed=1"
    ports: 
      - "26656:26656"
    expose:
      - "8081"
      - "26656"
      - "26660"
    volumes:
      - ./node1/config.json:/home/app/.pocket/config/config.json                      # Pocket Configuration file 
      - ./node1/chains.json:/home/app/.pocket/config/chains.json                      # Pocket chains.json
      - ./node1/:/home/app/.pocket/                                                   # Pocket Datadir 
      - ./node1/data/:/home/app/.pocket/data/                                         # Blockchain data
    restart: unless-stopped
    logging: *loki-logging

  loki:
    image: grafana/loki:latest
    container_name:  loki 
    volumes:
      - ./monitoring/loki/config.yaml:/etc/loki/local-config.yaml
    expose:
      - 3100
    ports:
      - "3100:3100"
    command: --config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    logging: *loki-logging

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus 
    user: "1000"
    volumes:
      - ./monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./monitoring/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    expose:
      - 9090
    restart: unless-stopped
    logging: *loki-logging

  grafana:
    image: grafana/grafana:latest
    container_name: grafana 
    user: "104"
    expose:
    - 3000
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/data:/var/lib/grafana
      - ./monitoring/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./monitoring/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=YOURADMINPASSWORD
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning/dashboards
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DATABASE_TYPE=sqlite3
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SERVER_DOMAIN=monitoring.${DOMAIN} 
      - GF_USERS_DEFAULT_THEME=dark
      - GF_SMTP_ENABLED=false
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
    restart: unless-stopped
    logging: *loki-logging

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter 
    expose:
      - 9100
    restart: unless-stopped
    logging: *loki-logging

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor 
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    restart: unless-stopped
    logging: *loki-logging

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    expose:
      - 9093
    volumes:
      - ./monitoring/alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yaml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    logging: *loki-logging
