version: '3'

services:

  nginx:
    image: poktnetwork/nginx:dispatch
    build: ../nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx/conf.d/10-pocket.conf:/etc/nginx/conf.d/default.conf"
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"

    networks:
      - pocket

  substrate-mainnet:
    image: polkasource/substrate-client:kusama-latest 
    expose:
      - "9933"
    volumes:
      - substrate-mainnet 
    command: "--rpc-external" 
    networks:
      - pocket

  pocket-service:
    image: poktnetwork/pocket-core:mvp-1.7
    ports:
      - "8081:8081"
    command: --disip ${POCKET_DISPATCH_IP:-dispatch.staging.pokt.network} --gid ${POCKET_SERVICE_GID} --ip localhost --disrport 443 --port 8081 --requestTimeout 0 --datadirectory datadir
    environment:
      POCKET_CORE_START_DELAY: 30 
      POCKET_CORE_CHAINS: '[ { "blockchain": { "name": "SUBSTRATE", "netid": "1", "version": "0" }, "url": "substrate-mainnet:9933"} ]'
    networks:
      - pocket

volumes:
  substrate-mainnet:

networks:
  pocket:
    driver: bridge
