version: '3.4'
services:
  pocket-core.public.dappnode.eth:
    image: 'pocket-core.public.dappnode.eth:0.0.1'
    build: ./build
    #command: --datadirectory datadir --disip dispatch.pokt.network --gid ${POCKET_CORE_SERVICE_GID:-MY_GID} --ip ${POCKET_CORE_SERVICE_IP:-127.0.0.1} --disrport 443 --port ${POCKET_CORE_SERVICE_PORT:-8081} --requestTimeout ${POCKET_CORE_REQUEST_TIMEOUT:-0} 
    ports:
      - "${POCKET_CORE_SERVICE_PORT:-8081}:8081"
    environment:
      POCKET_CORE_SERVICE_GID: 'MY_GID'
      POCKET_CORE_REQUEST_TIMEOUT: 0
      POCKET_CORE_CHAINS: '[]'
      POCKET_CORE_SERVICE_IP: '127.0.0.1'
      POCKET_CORE_SERVICE_PORT: 8081