version: '3'

services:

  nginx:
    image: poktnetwork/nginx:dispatch
    build: ../nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx/conf.d/10-pocket.conf:/etc/nginx/conf.d/default.conf"
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"

    networks:
      - pocket

  # https://docs.wavesplatform.com/en/waves-node/how-to-install-a-node/how-to-install-a-node.html 
  daps-mainnet:
    image: poktnetwork/daps:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAJOR_VERSION: 1.0.5
        SPECIFIC_VERSION: 1.0.5.7
    command: -listen -rest -server -printtoconsole -logtimestamps -logips -rpccorsdomain="*" -rpcbind="0.0.0.0" -rpcallowip="0.0.0.0/0"  
    volumes:
      - daps-mainnet:/home/DAPS_user/.dapscoin
    expose:
      - "53573"
    networks:
      - pocket

  pocket-service:
    image: poktnetwork/pocket-core:${ENV:-mvp-staging-latest}
    ports:
      - "8081:8081"
    
    command: --datadirectory datadir --disip ${POCKET_DISPATCH_IP:-dispatch.pokt.network} --gid ${POCKET_SERVICE_GID} --ip localhost --disrport 80 --port 8081 --requestTimeout 0
    environment:
      POCKET_CORE_START_DELAY: 50 
      POCKET_CORE_CHAINS: '[ { "blockchain": { "name": "DAPS", "netid": "MAINNET", "version": "0" }, "url": "daps-mainnet:53573" } ]'
    networks:
      - pocket

volumes:
  daps-mainnet:

networks:
  pocket:
    driver: bridge
